// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package slackconnector.actions;

import slackconnector.impl.SlackConnector;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class RegisterMessageListener extends CustomJavaAction<Boolean>
{
	private String authenticationToken;

	public RegisterMessageListener(IContext context, String authenticationToken)
	{
		super(context);
		this.authenticationToken = authenticationToken;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode logger = Core.getLogger(RegisterMessageListener.class.getName());
        SlackConnector connector = new SlackConnector(authenticationToken);
        connector.setLogger(logger);
        connector.registeringAListener(authenticationToken);
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "RegisterMessageListener";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
