// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testslackconnector.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TestSlackConnector module
	public static testslackconnector.proxies.SlackMessage createNewSlackMessage(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "TestSlackConnector.CreateNewSlackMessage", params);
			return result == null ? null : testslackconnector.proxies.SlackMessage.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void postSlackMessage(IContext context, testslackconnector.proxies.SlackMessage _slackMessage)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("SlackMessage", _slackMessage == null ? null : _slackMessage.getMendixObject());
			Core.execute(context, "TestSlackConnector.PostSlackMessage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sendDirectSlackMessage(IContext context, testslackconnector.proxies.SlackMessage _slackMessage)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("SlackMessage", _slackMessage == null ? null : _slackMessage.getMendixObject());
			Core.execute(context, "TestSlackConnector.SendDirectSlackMessage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}