// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package slackconnector.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the SlackConnector module

	public static java.lang.String getAuthenticationToken()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SlackConnector.AuthenticationToken");
	}
}