// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testslackconnector.proxies;

public class SlackMessage
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject slackMessageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestSlackConnector.SlackMessage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AuthenticationToken("AuthenticationToken"),
		ChannelName("ChannelName"),
		Message("Message"),
		DirectMessage("DirectMessage"),
		DirectMessageUsername("DirectMessageUsername");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SlackMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestSlackConnector.SlackMessage"));
	}

	protected SlackMessage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject slackMessageMendixObject)
	{
		if (slackMessageMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestSlackConnector.SlackMessage", slackMessageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestSlackConnector.SlackMessage");

		this.slackMessageMendixObject = slackMessageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SlackMessage.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static testslackconnector.proxies.SlackMessage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testslackconnector.proxies.SlackMessage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static testslackconnector.proxies.SlackMessage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testslackconnector.proxies.SlackMessage(context, mendixObject);
	}

	public static testslackconnector.proxies.SlackMessage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testslackconnector.proxies.SlackMessage.initialize(context, mendixObject);
	}

	public static java.util.List<testslackconnector.proxies.SlackMessage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testslackconnector.proxies.SlackMessage> result = new java.util.ArrayList<testslackconnector.proxies.SlackMessage>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestSlackConnector.SlackMessage" + xpathConstraint))
			result.add(testslackconnector.proxies.SlackMessage.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AuthenticationToken
	 */
	public final String getAuthenticationToken()
	{
		return getAuthenticationToken(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthenticationToken
	 */
	public final String getAuthenticationToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.AuthenticationToken.toString());
	}

	/**
	 * Set value of AuthenticationToken
	 * @param authenticationtoken
	 */
	public final void setAuthenticationToken(String authenticationtoken)
	{
		setAuthenticationToken(getContext(), authenticationtoken);
	}

	/**
	 * Set value of AuthenticationToken
	 * @param context
	 * @param authenticationtoken
	 */
	public final void setAuthenticationToken(com.mendix.systemwideinterfaces.core.IContext context, String authenticationtoken)
	{
		getMendixObject().setValue(context, MemberNames.AuthenticationToken.toString(), authenticationtoken);
	}

	/**
	 * @return value of ChannelName
	 */
	public final String getChannelName()
	{
		return getChannelName(getContext());
	}

	/**
	 * @param context
	 * @return value of ChannelName
	 */
	public final String getChannelName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ChannelName.toString());
	}

	/**
	 * Set value of ChannelName
	 * @param channelname
	 */
	public final void setChannelName(String channelname)
	{
		setChannelName(getContext(), channelname);
	}

	/**
	 * Set value of ChannelName
	 * @param context
	 * @param channelname
	 */
	public final void setChannelName(com.mendix.systemwideinterfaces.core.IContext context, String channelname)
	{
		getMendixObject().setValue(context, MemberNames.ChannelName.toString(), channelname);
	}

	/**
	 * @return value of Message
	 */
	public final String getMessage()
	{
		return getMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Message
	 */
	public final String getMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Message.toString());
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final void setMessage(String message)
	{
		setMessage(getContext(), message);
	}

	/**
	 * Set value of Message
	 * @param context
	 * @param message
	 */
	public final void setMessage(com.mendix.systemwideinterfaces.core.IContext context, String message)
	{
		getMendixObject().setValue(context, MemberNames.Message.toString(), message);
	}

	/**
	 * @return value of DirectMessage
	 */
	public final String getDirectMessage()
	{
		return getDirectMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of DirectMessage
	 */
	public final String getDirectMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.DirectMessage.toString());
	}

	/**
	 * Set value of DirectMessage
	 * @param directmessage
	 */
	public final void setDirectMessage(String directmessage)
	{
		setDirectMessage(getContext(), directmessage);
	}

	/**
	 * Set value of DirectMessage
	 * @param context
	 * @param directmessage
	 */
	public final void setDirectMessage(com.mendix.systemwideinterfaces.core.IContext context, String directmessage)
	{
		getMendixObject().setValue(context, MemberNames.DirectMessage.toString(), directmessage);
	}

	/**
	 * @return value of DirectMessageUsername
	 */
	public final String getDirectMessageUsername()
	{
		return getDirectMessageUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of DirectMessageUsername
	 */
	public final String getDirectMessageUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.DirectMessageUsername.toString());
	}

	/**
	 * Set value of DirectMessageUsername
	 * @param directmessageusername
	 */
	public final void setDirectMessageUsername(String directmessageusername)
	{
		setDirectMessageUsername(getContext(), directmessageusername);
	}

	/**
	 * Set value of DirectMessageUsername
	 * @param context
	 * @param directmessageusername
	 */
	public final void setDirectMessageUsername(com.mendix.systemwideinterfaces.core.IContext context, String directmessageusername)
	{
		getMendixObject().setValue(context, MemberNames.DirectMessageUsername.toString(), directmessageusername);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return slackMessageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testslackconnector.proxies.SlackMessage that = (testslackconnector.proxies.SlackMessage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestSlackConnector.SlackMessage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
